<div class="field customer_salutation required">
   <label class="label" for="customer_salutation">
       <span><?= $block->escapeHtml(__('Salutation')) ?></span>
   </label>
   <div class="control">
       <input type="text" name="customer_salutation" id="customer_salutation" value="" title="<?= $block->escapeHtmlAttr(__('Salutation')) ?>" class="input-text" data-validate="{required:true}">
   </div>
</div>